language: generic
services:
- docker
env:
  global:
  # DOCKER_USERNAME
  - secure: Emd9qv/K5dXXpyQ6UBO/GmKH/tjP1Ei+voOT+iDrKGYcmCoNSWw1f/19rzSm+yX3BErS7/WAL5eiB9XSGyf3izPzu7QHLh6kTGn/KA7t2ZY4jxrc3EQQAKQTXK0VH09eZjQzyTdl7r83Sm+P0UuA2MXpxM6ZWfmRz6zUGcnNDdvXhlKJ7lh/KufBbcN+snfaKQl3uhlTHoODbLq5KpwDOsM1p5wmSpKM01Vr6JYzZHY6uphRvYAb3ddZ/Be3vpViv3Izrg4aoZEVr9nW2IUFigWdafdCrh1QaKRVqcgmbHN1pgUxym5VdCh3BEfVwZl7ud0+swd7hBUO8p7dH+UQ7uorfRCo2Z5v+jcYi0Hz8+xQsZYDq38EYsMmZKVIrCrnzEDPMta7O/Npko2jHfITN6GNSiBuHrSqjbUgYkjJa9hA2XZsUIknRUGdny584bAd5j/8HhJY0OzF2dCILgDkYKwHBpxI/kG4Bw8fRSM9N14D0IWD+xdRmOsSv53kWwnmip3Zc0ZtIW7fc55PKVG4lsQi8afz8QmpF23BMW7akNyXPZEUUJ8IdbrbGSd6cavymtbSkucE2ggDNTkmZHFgM8Mi07++GfeolawugBS1f3a+7/xVUmqi6PJGuQsgqCgcuCqH8M4ht8DEq72znkmojnE+hXAzDpFucqupqN8J0B8=
  # DOCKER_PASSWORD
  - secure: MMZDT+l8fLxxp5ROLU6NiEwdHYiPK1tgo9/7bSJ6dM/8SSgRuJsu1tcD/DYex0H6Zx9Gb5heLrUVNuMolOX+yJNvhTH8LpX+7UnkySRDdYk5TH6dUvR+p0ra5amsb3qvZp+93Ir7FTPkkqMuRCJ6l49Fo/eq7dKO236/Twxj74u4RFUstnzX7CuDAOsCwFBUDQtvsoNGm9nsp8NyUfxHDwurZWAg48uu4T/JscUYjDvnyTQ8NvZNpO0awFEbjoCxPCfOB+7kA3obb0AioTJdjcTXDrxd6WPh+udMHyFKy7ReInaRjeFhSgKQgYYvb7mpTTawzg4w+hasZXQQPPIS8aWV5SjqJW2xXlc9SFKTCOCfDJDv33r+xZA68Fc7otqSUh693lDjoqpjtV/gnnvh9Mtu7ACCkyCeALgpId0HRo4UXrr9Z4O2UgO/Aa39uVNUaVb2/Vmax4HOnwuilTq63Pkcrp0vtot4jKxurGyaFfbYSkftl4NJ2xMXNpw1razRZGy+Paa4Pdg0sBGCkvNSeXIk0Wvykkzbb7gaPzZXNVK2gqac4C3DfbNiwz5ZNtLvjb9iTjlvCxtdyHSwTUnR3fJN8jSOSKg8l9rp/RzhhFOwBnXWxeYfJh22JerhscrTE5d60uWyjYiw/nfd62i9JuF37zAPL2DLAgortoRwW1c=
install:
- make ci-build
- make ci-run RUN_ARGS="-e OS_BASE_URL=http://localhost"
script:
- make ci-test
after_success:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make ci-push-tag TAG="${TRAVIS_PULL_REQUEST_BRANCH////_}";
  fi
deploy:
- provider: script
  script: make ci-push
  on:
    branch: master
